import React,{useEffect,useMemo,useState} from 'react'
import {Search,X,ChevronDown,ChevronLeft,ChevronRight,Inbox,LoaderCircle,AlertTriangle} from 'lucide-react'
import AnimatedValue from './AnimatedValue.jsx'

export function Button({children,variant='primary',icon:Icon,className='',...props}){return <button className={`btn btn-${variant} ${className}`} {...props}>{Icon&&<Icon size={16}/>}<span>{children}</span></button>}
export function PageHeader({eyebrow,title,description,actions}){return <div className="page-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="header-actions">{actions}</div></div>}
export function Card({children,className='',...props}){return <section className={`card ${className}`} {...props}>{children}</section>}
export function CardHead({title,subtitle,action}){return <div className="card-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action&&<div>{action}</div>}</div>}
export function StatCard({label,value,change,detail,icon:Icon,tone='blue'}){return <div className={`stat-card tone-${tone}`}><div className="stat-top"><span>{label}</span><span className="stat-icon"><Icon size={21}/></span></div><strong><AnimatedValue value={value}/></strong><div className="stat-foot"><span className="growth">{change}</span><span>{detail}</span></div></div>}
export function GradientCard({children,className=''}){return <div className={`gradient-card ${className}`}>{children}</div>}
export function ChartCard({title,subtitle,action,children}){return <Card><CardHead title={title} subtitle={subtitle} action={action}/>{children}</Card>}
export function StatusBadge({status}){const key=String(status||'').toLowerCase().replaceAll(' ','-');return <span className={`badge badge-${key}`}><i/>{status}</span>}
export function SearchInput({value,onChange,placeholder='Search...'}){return <label className="search-input"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
export function FilterDropdown({value,onChange,options,all='All',label}){return <label className="select-wrap">{label&&<span className="sr-only">{label}</span>}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">{all}</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select><ChevronDown size={15}/></label>}
export function ToggleSwitch({checked,onChange,label}){return <button type="button" role="switch" aria-checked={checked} aria-label={label} className={`toggle ${checked?'on':''}`} onClick={()=>onChange(!checked)}><span/></button>}
export function Modal({title,children,onClose,width='540px'}){useEffect(()=>{const h=e=>e.key==='Escape'&&onClose();document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h)},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" style={{maxWidth:width}} role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20}/></button></div>{children}</div></div>}
export function ConfirmDialog({title,description,onConfirm,onClose,confirm='Confirm'}){return <Modal title={title} onClose={onClose}><p className="muted">{description}</p><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="danger" onClick={()=>{onConfirm();onClose()}}>{confirm}</Button></div></Modal>}
export function EmptyState({title='No records found',description='Try adjusting your filters or add a new record.'}){return <div className="empty-state"><Inbox size={28}/><h3>{title}</h3><p>{description}</p></div>}
export function LoadingSkeleton(){return <div className="skeleton"/>}
export function AlertCard({icon:Icon,title,description,checked,onChange}){return <div className="alert-option"><span className="alert-option-icon"><Icon size={19}/></span><div><strong>{title}</strong><p>{description}</p></div><ToggleSwitch label={title} checked={checked} onChange={onChange}/></div>}
export function DataTable({columns,rows,search='',pageSize=8,empty,sortDefault}){
  const [sort,setSort]=useState(sortDefault||'');const [desc,setDesc]=useState(false);const [page,setPage]=useState(1)
  useEffect(()=>setPage(1),[rows.length,search])
  const sorted=useMemo(()=>sort?[...rows].sort((a,b)=>{const aa=String(a[sort]??''),bb=String(b[sort]??'');return (desc?-1:1)*aa.localeCompare(bb,undefined,{numeric:true})}):rows,[rows,sort,desc])
  const total=Math.max(1,Math.ceil(sorted.length/pageSize));const current=Math.min(page,total);const visible=sorted.slice((current-1)*pageSize,current*pageSize)
  return <><div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c.key} onClick={()=>{if(!c.sortable)return;setDesc(sort===c.key?!desc:false);setSort(c.key)}} className={c.sortable?'sortable':''}>{c.label}{sort===c.key?' '+(desc?'↓':'↑'):''}</th>)}</tr></thead><tbody>{visible.map((row,i)=><tr key={row.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):row[c.key]}</td>)}</tr>)}</tbody></table>{!visible.length&&(empty||<EmptyState/>)}</div>{sorted.length>pageSize&&<div className="table-pagination"><span>Showing {(current-1)*pageSize+1}–{Math.min(current*pageSize,sorted.length)} of {sorted.length}</span><div><button disabled={current===1} onClick={()=>setPage(p=>p-1)} aria-label="Previous page"><ChevronLeft size={16}/></button><span>{current} / {total}</span><button disabled={current===total} onClick={()=>setPage(p=>p+1)} aria-label="Next page"><ChevronRight size={16}/></button></div></div>}</>
}
