import React,{Suspense,lazy} from 'react'
import {Routes,Route,Navigate} from 'react-router-dom'
import AppLayout from './layouts/AppLayout.jsx'
import SplashScreen from './components/SplashScreen.jsx'
const Home=lazy(()=>import('./pages/Home.jsx'))
const Municipalities=lazy(()=>import('./portals/province/Municipalities.jsx'))
const Comparison=lazy(()=>import('./portals/province/Comparison.jsx'))
const ReportReview=lazy(()=>import('./portals/province/ReportReview.jsx'))
const Users=lazy(()=>import('./portals/province/Users.jsx'))
const Consumers=lazy(()=>import('./pages/Consumers.jsx'))
const ConsumerDetails=lazy(()=>import('./pages/Consumers.jsx').then(m=>({default:m.ConsumerDetails})))
const MeterReadings=lazy(()=>import('./pages/MeterReadings.jsx'))
const Billing=lazy(()=>import('./pages/Billing.jsx'))
const Payments=lazy(()=>import('./pages/Payments.jsx'))
const Alerts=lazy(()=>import('./pages/Alerts.jsx'))
const TariffTiers=lazy(()=>import('./pages/TariffTiers.jsx'))
const Reports=lazy(()=>import('./pages/Reports.jsx'))
const Settings=lazy(()=>import('./pages/Settings.jsx'))
const ServiceArea=lazy(()=>import('./pages/ServiceArea.jsx'))
const HighConsumption=lazy(()=>import('./pages/HighConsumption.jsx'))
const MonthlyReports=lazy(()=>import('./pages/MonthlyReports.jsx'))
const AuditLogs=lazy(()=>import('./pages/AuditLogs.jsx'))
const Zones=lazy(()=>import('./portals/operations/Zones.jsx'))
const RouteManagement=lazy(()=>import('./portals/operations/Routes.jsx'))
const ServiceRequests=lazy(()=>import('./portals/operations/ServiceRequests.jsx'))
const WorkOrders=lazy(()=>import('./portals/operations/WorkOrders.jsx'))
const CitizenHome=lazy(()=>import('./portals/citizen/CitizenHome.jsx'))
const CitizenBills=lazy(()=>import('./portals/citizen/CitizenBills.jsx'))
const CitizenRequests=lazy(()=>import('./portals/citizen/CitizenRequests.jsx'))
const CitizenCalculator=lazy(()=>import('./portals/citizen/CitizenCalculator.jsx'))
const CitizenAccount=lazy(()=>import('./portals/citizen/CitizenAccount.jsx'))
const TellerDashboard=lazy(()=>import('./portals/teller/TellerDashboard.jsx'))
const TellerSearch=lazy(()=>import('./portals/teller/TellerSearch.jsx'))
const TellerReceipts=lazy(()=>import('./portals/teller/TellerReceipts.jsx'))
const TellerWindow=lazy(()=>import('./portals/teller/TellerWindow.jsx'))
const ReaderDashboard=lazy(()=>import('./portals/reader/ReaderDashboard.jsx'))
const ReaderRoute=lazy(()=>import('./portals/reader/ReaderRoute.jsx'))
const ReaderSearch=lazy(()=>import('./portals/reader/ReaderSearch.jsx'))
const ReadingForm=lazy(()=>import('./portals/reader/ReadingForm.jsx'))
const ReaderReports=lazy(()=>import('./portals/reader/ReaderReports.jsx'))
const ReaderSync=lazy(()=>import('./portals/reader/ReaderSync.jsx'))
const ReaderProfile=lazy(()=>import('./portals/reader/ReaderProfile.jsx'))
const Login=lazy(()=>import('./pages/Login.jsx'))
export default function App(){return <Suspense fallback={<SplashScreen/>}><Routes><Route path="/login" element={<Login/>}/><Route element={<AppLayout/>}><Route path="/" element={<Home/>}/><Route path="/service-area" element={<ServiceArea/>}/><Route path="/consumers" element={<Consumers/>}/><Route path="/consumers/:id" element={<ConsumerDetails/>}/><Route path="/meter-readings" element={<MeterReadings/>}/><Route path="/billing" element={<Billing/>}/><Route path="/payments" element={<Payments/>}/><Route path="/alerts" element={<Alerts/>}/><Route path="/tariff-tiers" element={<TariffTiers/>}/><Route path="/reports" element={<Reports/>}/><Route path="/high-consumption" element={<HighConsumption/>}/><Route path="/monthly-reports" element={<MonthlyReports/>}/><Route path="/monthly-reports/:id" element={<ReportReview/>}/><Route path="/audit-logs" element={<AuditLogs/>}/><Route path="/zones" element={<Zones/>}/><Route path="/routes" element={<RouteManagement/>}/><Route path="/service-requests" element={<ServiceRequests/>}/><Route path="/work-orders" element={<WorkOrders/>}/><Route path="/municipalities" element={<Municipalities/>}/><Route path="/comparison" element={<Comparison/>}/><Route path="/users" element={<Users/>}/><Route path="/citizen" element={<CitizenHome/>}/><Route path="/citizen/bills" element={<CitizenBills/>}/><Route path="/citizen/requests" element={<CitizenRequests/>}/><Route path="/citizen/calculator" element={<CitizenCalculator/>}/><Route path="/citizen/account" element={<CitizenAccount/>}/><Route path="/teller" element={<TellerDashboard/>}/><Route path="/teller/search" element={<TellerSearch/>}/><Route path="/teller/receipts" element={<TellerReceipts/>}/><Route path="/teller/window" element={<TellerWindow/>}/><Route path="/reader" element={<ReaderDashboard/>}/><Route path="/reader/route" element={<ReaderRoute/>}/><Route path="/reader/search" element={<ReaderSearch/>}/><Route path="/reader/read/:id" element={<ReadingForm/>}/><Route path="/reader/reports" element={<ReaderReports/>}/><Route path="/reader/sync" element={<ReaderSync/>}/><Route path="/reader/profile" element={<ReaderProfile/>}/><Route path="/reader/readings" element={<Navigate to="/reader/route" replace/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes></Suspense>}
